config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  get 'home/index'
  post 'my_survivor/' => 'survivors#create'
  get 'my_survivor/' => 'survivors#new'

  get 'play/' => 'play#index'
  get 'play/get_last_info' => 'play#get_last_info'

  root to: "home#index"
end

app/models/survivor.rb
class Survivor < ActiveRecord::Base

  belongs_to :game_history
  belongs_to :zone, foreign_key: :zone_code, primary_key: :zone_code

  def to_json_load
    {
      x: x || 0,
      y: y || 0
    }
  end
end

app/controllers/survivors_controller.rb
class SurvivorsController < ApplicationController

  before_action :has_game_history

  def new
    @survivor = Survivor.new
  end

  def create
    @game_history = GameHistory.init current_user, survivor_params

    redirect_to play_path
  end

  def survivor_params
     params.require(:survivor).permit( :name, :last_name, :sex, :skin )
  end

  def has_game_history
    if current_user.game_history
      redirect_to play_path
    end
  end
end

app/helpers/survivors_helper.rb
module SurvivorsHelper

  def collect_tez
    [0]
  end
end

app/views/survivors/new.html.erb
<% content_for :files_imported do %>
  <%= javascript_include_tag 'survivors' %>
<% end %>

<h1>Survivors#new</h1>
<%= form_for @survivor ,url: my_survivor_path do |f| %>
  <%= f.label t('models.survivor.name') %>
  <%= f.text_field :name, autofocus: true %><br>

  <%= f.label t('models.survivor.last_name') %>
  <%= f.text_field :last_name %><br>

  <%= f.label :sex %><br>
  <%= t('models.survivor.sexs.m') %>
  <%= f.radio_button :sex, "m" , checked: "checked", class: "change_sex" %>
  <%= t('models.survivor.sexs.f') %>
  <%= f.radio_button :sex, "f" , class: "change_sex" %><br>

  <%= f.label :skin %><br>
  <% collect_tez.each do |n| %>
    <%= n %>
    <%= f.radio_button :skin, n , checked: "checked" , class: "change_skin" %>
  <% end %><br>

  <canvas width="32" height="64" id="avatar"></canvas><br>

  <%= link_to "Turn Left","javascript:avatar.turnLeft();" %>
  <%= link_to "Turn Right","javascript:avatar.turnRight();" %><br>

  <%= f.submit %>
<% end %>